
export const quotes = [
    { text: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
    { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa" },
    { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "Learning is never done without errors and defeat.", author: "Vladimir Lenin" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
    { text: "Learning is like rowing upstream; not to advance is to drop back.", author: "Chinese Proverb" },
    { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Your limit—it's just your imagination.", author: "Unknown" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { text: "Great things never come from comfort zones.", author: "Unknown" },
    { text: "Sometimes later becomes never. Do it now.", author: "Unknown" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    { text: "Dream bigger. Do bigger.", author: "Unknown" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { text: "Do something today that your future self will thank you for.", author: "Unknown" },
    { text: "Little things make big days.", author: "Unknown" },
    { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
    { text: "Don't wait for opportunity. Create it.", author: "Unknown" },
    { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
    { text: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
    { text: "Everything you need is already inside you.", author: "Unknown" },
    { text: "Never give up on a dream just because of the time it will take to accomplish it.", author: "Earl Nightingale" },
    { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
    { text: "Stay positive, work hard, make it happen.", author: "Unknown" },
    { text: "Your only limit is you.", author: "Unknown" },
    { text: "You are capable of more than you know.", author: "Unknown" },
    { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
    { text: "It's not about how bad you want it. It's about how hard you're willing to work for it.", author: "Unknown" },
    { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Success is what happens after you have survived all of your disappointments.", author: "Unknown" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "If you don't build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Success is not just about what you accomplish in your life; it's about what you inspire others to do.", author: "Unknown" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
    { text: "Small progress is still progress.", author: "Unknown" },
    { text: "Be stubborn about your goals and flexible about your methods.", author: "Unknown" },
    { text: "One day or day one. You decide.", author: "Unknown" },
    { text: "Everything comes to him who hustles while he waits.", author: "Thomas Edison" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
    { text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
    { text: "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", author: "Henry Ford" },
    { text: "There is no royal road to anything. One thing at a time, all things in succession. That which grows fast, withers as rapidly. That which grows slowly, endures.", author: "Josiah Gilbert Holland" },
    { text: "I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody.", author: "Herbert Bayard Swope" },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
    { text: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", author: "Theodore N. Vail" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
    { text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
    { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
    { text: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
    { text: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
    { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
    { text: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
    { text: "Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.", author: "Helen Keller" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { text: "Do what you love and the money will follow.", author: "Marsha Sinetar" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "To be successful you must accept all challenges that come your way. You can’t just accept the ones you like.", author: "Mike Gafka" },
    { text: "Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better.", author: "Jim Rohn" },
    { text: "I have failed over and over and over again in my life and that is why I succeed.", author: "Michael Jordan" },
    { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
    { text: "Never give up on what you really want to do. The person with big dreams is more powerful than one with all the facts.", author: "Unknown" },
    { text: "Don’t let the noise of others’ opinions drown out your own inner voice.", author: "Steve Jobs" },
    { text: "Be so good they can’t ignore you.", author: "Steve Martin" },
    { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "If you focus on results, you will never change. If you focus on change, you will get results.", author: "Jack Dixon" },
    { text: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
    { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker" },
    { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
    { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
    { text: "The mind that opens to a new idea never returns to its original size.", author: "Albert Einstein" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "Continuous learning is the minimum requirement for success in any field.", author: "Brian Tracy" },
    { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
    { text: "The more you learn, the more you earn.", author: "Warren Buffett" },
    { text: "Self-education is, I firmly believe, the only kind of education there is.", author: "Isaac Asimov" },
    { text: "You learn something every day if you pay attention.", author: "Ray LeBlond" },
    { text: "Learning today for a better tomorrow.", author: "Unknown" },
    { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
    { text: "Every student can learn, just not on the same day, or the same way.", author: "George Evans" },
    { text: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
    { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
    { text: "A mind is a fire to be kindled, not a vessel to be filled.", author: "Plutarch" },
    { text: "Aim for success, not perfection. Never give up your right to be wrong, because then you will lose the ability to learn new things and move forward with your life.", author: "Dr. David M. Burns" },
    { text: "You never stop learning. If you have a teacher, you never stop being a student.", author: "Elisabeth Rohm" },
    { text: "The great aim of education is not knowledge but action.", author: "Herbert Spencer" },
    { text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
    { text: "He who learns but does not think, is lost! He who thinks but does not learn is in great danger.", author: "Confucius" },
    { text: "We now accept the fact that learning is a lifelong process of keeping abreast of change. And the most pressing task is to teach people how to learn.", author: "Peter Drucker" },
    { text: "In a time of drastic change it is the learners who inherit the future. The learned usually find themselves equipped to live in a world that no longer exists.", author: "Eric Hoffer" },
    { text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy" },
    { text: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.", author: "Henry Ford" },
    { text: "Education is what survives when what has been learned has been forgotten.", author: "B. F. Skinner" },
    { text: "Learning is not spectacle, but an experience.", author: "Unknown" },
    { text: "If you think education is expensive, try ignorance.", author: "Derek Bok" },
    { text: "The education of even a small child, therefore, does not aim at preparing him for school, but for life.", author: "Maria Montessori" },
    { text: "A man’s mind, once stretched by a new idea, never regains its original dimensions.", author: "Oliver Wendell Holmes Jr." },
    { text: "Learning is the only thing the mind never exhausts, never fears, and never regrets.", author: "Leonardo da Vinci" },
    { text: "The aim of education should be to teach us rather how to think, than what to think — rather to improve our minds, so as to enable us to think for ourselves, than to load the memory with thoughts of other men.", author: "Bill Beattie" },
    { text: "The more I read, the more I acquire, the more I am certain that I know nothing.", author: "Voltaire" },
    { text: "The teacher who is indeed wise does not bid you to enter the house of his wisdom but rather leads you to the threshold of your mind.", author: "Khalil Gibran" },
    { text: "Learning is a weightless treasure you can always carry with you.", author: "Unknown" },
    { text: "I'm not failing, I'm just learning how not to do it.", author: "Unknown" },
    { text: "Every day is a chance to learn something new.", author: "Unknown" },
    { text: "The world is your classroom.", author: "Unknown" },
    { text: "Curiosity is the engine of achievement.", author: "Ken Robinson" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "Excellence is not a skill. It is an attitude.", author: "Ralph Marston" },
    { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
    { text: "Teachers open the door, but you must enter by yourself.", author: "Chinese Proverb" },
    { text: "The purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
    { text: "The direction in which education starts a man will determine his future life.", author: "Plato" },
    { text: "The objective of education is to prepare the young to educate themselves throughout their lives.", author: "Robert M. Hutchins" },
    { text: "Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family.", author: "Kofi Annan" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "Upon the education of the people of this country, the fate of this country depends.", author: "Benjamin Disraeli" },
    { text: "Education is the manifestation of perfection already in man.", author: "Swami Vivekananda" },
    { text: "A well-educated mind will always have more questions than answers.", author: "Helen Keller" },
    { text: "Education’s purpose is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
    { text: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
    { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
    { text: "The best thing about a boolean is even if you are wrong, you are only off by a bit.", author: "Anonymous" },
    { text: "Programming is the art of telling another human what one wants the computer to do.", author: "Donald Knuth" },
    { text: "The most important property of a program is whether it accomplishes the intention of its user.", author: "C.A.R. Hoare" },
    { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
    { text: "Code is like humor. When you have to explain it, it’s bad.", author: "Cory House" },
    { text: "Fix the cause, not the symptom.", author: "Steve Maguire" },
    { text: "Optimism is an occupational hazard of programming: feedback is the treatment.", author: "Kent Beck" },
    { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman" },
    { text: "Before software can be reusable it first has to be usable.", author: "Ralph Johnson" },
    { text: "Computers are good at following instructions, but not at reading your mind.", author: "Donald Knuth" },
    { text: "One man’s constant is another man’s variable.", author: "Alan Perlis" },
    { text: "If you think your users are idiots, only idiots will use it.", author: "Linus Torvalds" },
    { text: "Software is a great combination between artistry and engineering.", author: "Bill Gates" },
    { text: "Programmer: A machine that turns coffee into code.", author: "Unknown" },
    { text: "Computers are incredibly fast, accurate, and stupid. Human beings are incredibly slow, inaccurate, and brilliant. Together they are powerful beyond imagination.", author: "Albert Einstein" },
    { text: "Everything is a learning experience.", author: "Unknown" },
    { text: "Mistakes are proof that you are trying.", author: "Unknown" },
    { text: "Don't wish it were easier, wish you were better.", author: "Jim Rohn" },
    { text: "The way to learn is by doing.", author: "Unknown" },
    { text: "Be the student until you are the master, then be the student again.", author: "Unknown" },
    { text: "Your brain is a muscle; use it.", author: "Unknown" },
    { text: "Growth mindset is the key to life.", author: "Unknown" },
    { text: "Challenge yourself every day.", author: "Unknown" },
    { text: "Persistence is the path to mastery.", author: "Unknown" },
    { text: "Curiosity killed the cat, but satisfaction brought it back.", author: "Proverb" },
    { text: "The more you know, the more you realize you don't know.", author: "Aristotle" },
    { text: "Learning is the bridge between dreams and reality.", author: "Unknown" },
    { text: "The best investment is in yourself.", author: "Unknown" },
    { text: "Education is not a destination, it's a journey.", author: "Unknown" },
    { text: "Knowledge is the only thing that grows when shared.", author: "Unknown" },
    { text: "A little progress each day adds up to big results.", author: "Unknown" },
    { text: "Do not fear failure but rather fear not trying.", author: "Roy T. Bennett" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "If you want to be the best, you have to do things that other people aren’t willing to do.", author: "Michael Phelps" },
    { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { text: "The future belongs to the curious.", author: "Unknown" },
    { text: "Your potential is endless.", author: "Unknown" },
    { text: "Every master was once a disaster.", author: "Unknown" },
    { text: "Stay curious, stay inspired.", author: "Unknown" },
    { text: "Hard work opens doors that luck cannot.", author: "Unknown" },
    { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { text: "Confidence comes from discipline and training.", author: "Robert Kiyosaki" },
    { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { text: "The hard road leads to the easy life. The easy road leads to the hard life.", author: "Unknown" },
    { text: "You get what you work for, not what you wish for.", author: "Unknown" },
    { text: "Great things take time.", author: "Unknown" },
    { text: "Believe in the power of yet.", author: "Carol Dweck" },
    { text: "Fail forward.", author: "Denzel Washington" },
    { text: "Your attitude determines your altitude.", author: "Zig Ziglar" },
    { text: "The only limit is the one you set for yourself.", author: "Unknown" },
    { text: "Mindset is everything.", author: "Unknown" },
    { text: "Dream, Plan, Execute.", author: "Unknown" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "Strive for progress, not perfection.", author: "Unknown" },
    { text: "The secret to getting ahead is getting started.", author: "Mark Twain" },
    { text: "I find that the more I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
    { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
    { text: "The best project you will ever work on is you.", author: "Unknown" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "If you don't value your time, neither will others.", author: "Kim Garst" },
    { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { text: "Small steps in the right direction can turn out to be the biggest steps of your life.", author: "Unknown" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "You have to be at your strongest when you're at your weakest.", author: "Unknown" },
    { text: "It's not the load that breaks you, it's the way you carry it.", author: "Lou Holtz" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "The only way to reach the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "You are confined only by the walls you build yourself.", author: "Unknown" },
    { text: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche" },
    { text: "If it's important to you, you will find a way. If not, you will find an excuse.", author: "Unknown" },
    { text: "Make each day your masterpiece.", author: "John Wooden" },
    { text: "Do it with passion or not at all.", author: "Unknown" },
    { text: "Be the primary choice in a world of secondary ones.", author: "Unknown" },
    { text: "Don't decrease the goal. Increase the effort.", author: "Unknown" },
    { text: "Hustle until your idols become your rivals.", author: "Unknown" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "Success is not for the lazy.", author: "Unknown" },
    { text: "Obsessed is a word the lazy use to describe the dedicated.", author: "Unknown" },
    { text: "Work until you no longer have to introduce yourself.", author: "Unknown" },
    { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
    { text: "Win from within.", author: "Unknown" },
    { text: "Difficult doesn't mean impossible. It simply means that you have to work hard.", author: "Unknown" },
    { text: "No pressure, no diamonds.", author: "Thomas Carlyle" },
    { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Go as far as you can see; when you get there, you'll be able to see further.", author: "Thomas Carlyle" },
    { text: "The difference between a stumbling block and a stepping stone is how you use them.", author: "Unknown" },
    { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
    { text: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    { text: "Don't let your struggle become your identity.", author: "Unknown" },
    { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
    { text: "Nothing in the world can take the place of Persistence.", author: "Calvin Coolidge" },
    { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
    { text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent Van Gogh" },
    { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
    { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
    { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "He who would learn to fly one day must first learn to stand and walk and run and climb and dance; one cannot fly into flying.", author: "Friedrich Nietzsche" },
    { text: "The higher we soar the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
    { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
    { text: "The state of your life is nothing more than a reflection of your state of mind.", author: "Wayne Dyer" },
    { text: "You are the master of your destiny. You can influence, direct and control your own environment. You can make your life what you want it to be.", author: "Napoleon Hill" },
    { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
    { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { text: "Identify your problems, but give your power and energy to solutions.", author: "Tony Robbins" },
    { text: "There is no such thing as failure. There are only results.", author: "Tony Robbins" },
    { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
    { text: "Comfort is the enemy of achievement.", author: "Farrah Gray" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { text: "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.", author: "Joel Brown" },
    { text: "Focus on where you want to go, not on what you fear.", author: "Anthony Robbins" },
    { text: "The problem is not the problem. The problem is your attitude about the problem.", author: "Jack Sparrow" },
    { text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
    { text: "Everything you've ever wanted is sitting on the other side of fear.", author: "George Addair" },
    { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
    { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon 'em.", author: "William Shakespeare" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Henry David Thoreau" },
    { text: "Every problem is an opportunity in disguise.", author: "John Adams" },
    { text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
    { text: "Work like there is someone working twenty-four hours a day to take it away from you.", author: "Mark Cuban" },
    { text: "The vision must be followed by the venture.", author: "Vance Havner" },
    { text: "The successful man will profit from his mistakes and try again in a different way.", author: "Dale Carnegie" },
    { text: "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.", author: "Jim Rohn" },
    { text: "Your work is to discover your world and then with all your heart give yourself to it.", author: "Buddha" },
    { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
    { text: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins" },
    { text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
    { text: "Success is not a destination, but the road that you're on. Being successful means that you're working hard and walking your walk. You can only live your dream by working hard towards it. That's living your dream.", author: "Marlon Wayans" },
    { text: "Motivation alone is not enough. If you have an idiot and you motivate him, now you have a motivated idiot.", author: "Jim Rohn" },
    { text: "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
    { text: "Don't let the behavior of others destroy your inner peace.", author: "Dalai Lama" },
    { text: "Our greatest glory is not in never failing, but in rising every time we fail.", author: "Confucius" },
    { text: "The simple life is its own reward.", author: "Unknown" },
    { text: "Peace of mind is the ultimate success.", author: "Unknown" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Be present in all things and thankful for all things.", author: "Maya Angelou" },
    { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
    { text: "Every leaf speaks bliss to me, fluttering from the autumn tree.", author: "Emily Bronte" },
    { text: "In every walk with nature one receives far more than he seeks.", author: "John Muir" },
    { text: "Keep close to Nature's heart... and break clear away, once in a while, and climb a mountain or spend a week in the woods. Wash your spirit clean.", author: "John Muir" },
    { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
    { text: "The best thing one can do when it's raining is to let it rain.", author: "Henry Wadsworth Longfellow" },
    { text: "He who is brave is free.", author: "Seneca" },
    { text: "If a task is once begun, never leave it till it's done. Be the labor great or small, do it well or not at all.", author: "Unknown" },
    { text: "Don't judge a book by its cover.", author: "Proverb" },
    { text: "Where there is a will, there is a way.", author: "Proverb" },
    { text: "The higher the boulder, the greater the view.", author: "Unknown" },
    { text: "Consistency is more important than intensity.", author: "Unknown" },
    { text: "Be the reason someone smiles today.", author: "Unknown" },
];
